name: CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          # Only using snapshot for now since we're using cutting edge TS features
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Cask
      run: git clone https://github.com/cask/cask ~/.cask

    - name: Add to path
      run: echo "${HOME}/.cask/bin" >> $GITHUB_PATH

    - name: Run tests
      run:
        # XXX: This is really dumb but building grammars with C++ fails to load unless I do this
        mkdir wtf/;
        cp /lib/x86_64-linux-gnu/libstdc++.so.6 wtf/;
        LD_LIBRARY_PATH=wtf/ make test
